plugins:
  - babel
env:
  browser: true
  jest/globals: true
  es2021: true
extends:
  - airbnb-base
  - 'plugin:jest/recommended'
  - prettier
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {}
